# Generated by Django 5.2.6 on 2025-09-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='productos/'),
        ),
    ]
