# Generated by Django 5.2.6 on 2025-09-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='identificacion',
        ),
    ]
