# Generated by Django 5.2.6 on 2025-09-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inventario_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='categorias/'),
        ),
    ]
